apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-nextjs-app-deployment
  labels:
    app: docker-nextjs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-nextjs-app
  template:
    metadata:
      labels:
        app: docker-nextjs-app
    spec:
      containers:
      - name: docker-nextjs-app
        image: ernestohegi/docker-nextjs-app:latest
        ports:
        - containerPort: 80

